import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { configNeedsRegeneration, regenerateConfig } from '../generator';

interface GeneratedCliProxyConfig {
  'oauth-model-alias'?: Record<string, Array<{ name: string; alias: string; fork?: boolean }>>;
  payload?: {
    override?: Array<{
      models: Array<{ name: string; protocol?: string }>;
      params: Record<string, unknown>;
    }>;
    [section: string]: unknown;
  };
  [key: string]: unknown;
}

describe('Codex user routing config generation', () => {
  let testHome: string;
  let originalCcsHome: string | undefined;
  let generatedConfigPath: string;
  let generatedAuthDir: string;

  beforeEach(() => {
    testHome = fs.mkdtempSync(path.join(os.tmpdir(), 'ccs-codex-routing-'));
    originalCcsHome = process.env.CCS_HOME;
    process.env.CCS_HOME = testHome;
    const ccsDir = path.join(testHome, '.ccs');
    const cliproxyDir = path.join(ccsDir, 'cliproxy');
    fs.mkdirSync(cliproxyDir, { recursive: true });
    generatedConfigPath = path.join(cliproxyDir, 'config.yaml');
    generatedAuthDir = path.join(cliproxyDir, 'auth');

    fs.writeFileSync(
      path.join(ccsDir, 'config.yaml'),
      `version: 14
cliproxy:
  oauth_model_alias:
    codex:
      - name: gpt-5.6-sol
        alias: gpt-5.6-sol-fast
        fork: true
  payload:
    override:
      - models:
          - name: gpt-5.6-sol-fast
            protocol: codex
        params:
          service_tier: priority
`,
      'utf8'
    );
  });

  afterEach(() => {
    if (originalCcsHome === undefined) {
      delete process.env.CCS_HOME;
    } else {
      process.env.CCS_HOME = originalCcsHome;
    }
    fs.rmSync(testHome, { recursive: true, force: true });
  });

  function readGeneratedConfig(): GeneratedCliProxyConfig {
    return yaml.load(fs.readFileSync(generatedConfigPath, 'utf8')) as GeneratedCliProxyConfig;
  }

  it('generates external client alias semantics with a Codex-only priority override', () => {
    regenerateConfig(8317, {
      configPath: generatedConfigPath,
      authDir: generatedAuthDir,
    });

    const generated = readGeneratedConfig();
    expect(generated['oauth-model-alias']?.codex).toEqual([
      { name: 'gpt-5.6-sol', alias: 'gpt-5.6-sol-fast', fork: true },
    ]);
    expect(generated.payload?.override).toEqual([
      {
        models: [{ name: 'gpt-5.6-sol-fast', protocol: 'codex' }],
        params: { service_tier: 'priority' },
      },
    ]);
    expect(
      generated.payload?.override?.some((rule) =>
        rule.models.some((model) => model.name === 'gpt-5.6-sol')
      )
    ).toBe(false);
  });

  it('rewrites CCS-owned aliases, preserves user payload rules, and reaches a fixed point', () => {
    fs.writeFileSync(
      generatedConfigPath,
      `# CLIProxyAPI config generated by CCS v20
port: 8317
api-keys:
  - "ccs-internal-managed"
auth-dir: "${generatedAuthDir}"
oauth-model-alias:
  codex:
    - name: existing-upstream
      alias: existing-client
    - name: gpt-5.6-sol
      alias: gpt-5.6-sol-fast
  future-provider:
    - name: future-upstream
      alias: future-client
payload:
  default:
    - models:
        - name: existing-client
      params:
        temperature: 0.2
  override:
    - models:
        - name: gpt-5.6-sol-fast
          protocol: codex
      params:
        service_tier: standard
    - models:
        - name: manual-client
          protocol: codex
      params:
        custom_flag: preserved
`,
      'utf8'
    );

    expect(configNeedsRegeneration()).toBe(true);
    regenerateConfig(8317, {
      configPath: generatedConfigPath,
      authDir: generatedAuthDir,
    });
    const first = readGeneratedConfig();

    expect(first['oauth-model-alias']?.codex).toEqual([
      { name: 'gpt-5.6-sol', alias: 'gpt-5.6-sol-fast', fork: true },
    ]);
    expect(first['oauth-model-alias']?.['future-provider']).toBeUndefined();
    expect(first.payload?.default).toBeDefined();
    expect(first.payload?.override).toEqual([
      {
        models: [{ name: 'gpt-5.6-sol-fast', protocol: 'codex' }],
        params: { service_tier: 'priority' },
      },
      {
        models: [{ name: 'manual-client', protocol: 'codex' }],
        params: { custom_flag: 'preserved' },
      },
    ]);
    expect(configNeedsRegeneration()).toBe(false);

    regenerateConfig(8317, {
      configPath: generatedConfigPath,
      authDir: generatedAuthDir,
    });
    expect(readGeneratedConfig()).toEqual(first);
  });
});
