import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, describe, expect, it } from 'bun:test';
import type { CompositeTierConfig } from '../../../config/schemas/cliproxy';
import {
  DuplicateOAuthAliasPoolHopError,
  buildOrderedOAuthAliasPool,
  generateOrderedOAuthAliasPoolYaml,
  regenerateConfig,
  runtimeSupportsOrderedOAuthAliasPool,
} from '../generator';

const tempDirs: string[] = [];

afterEach(() => {
  for (const tempDir of tempDirs.splice(0)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

describe('ordered OAuth alias-pool projection', () => {
  it('builds a two-channel chain in primary-first order', () => {
    // Given
    const tier: CompositeTierConfig = {
      provider: 'claude',
      model: 'claude-opus-4-8',
      fallback_chain: [{ provider: 'codex', model: 'gpt-5.5' }],
    };

    // When
    const pool = buildOrderedOAuthAliasPool('ccs-opus', tier);

    // Then
    expect(pool.hops).toEqual([
      { channel: 'claude', model: 'claude-opus-4-8' },
      { channel: 'codex', model: 'gpt-5.5' },
    ]);
  });

  it('emits channel entries in exact quality-and-cost order', () => {
    // Given
    const pool = buildOrderedOAuthAliasPool('ccs-plan', {
      provider: 'claude',
      model: 'claude-opus-4-8',
      fallback_chain: [
        { provider: 'codex', model: 'gpt-5.5' },
        { provider: 'kimi', model: 'kimi-k2.7-code' },
      ],
    });

    // When
    const yaml = generateOrderedOAuthAliasPoolYaml(pool, { kind: 'ordered' });

    // Then
    expect(yaml.indexOf('  claude:')).toBeLessThan(yaml.indexOf('  codex:'));
    expect(yaml.indexOf('  codex:')).toBeLessThan(yaml.indexOf('  kimi:'));
  });

  it('rejects duplicate provider and model hops', () => {
    // Given
    const tier: CompositeTierConfig = {
      provider: 'claude',
      model: 'claude-opus-4-8',
      fallback_chain: [{ provider: 'claude', model: 'claude-opus-4-8' }],
    };

    // When / Then
    expect(() => buildOrderedOAuthAliasPool('ccs-opus', tier)).toThrow(
      DuplicateOAuthAliasPoolHopError
    );
  });

  it('supports ordered pools on fork runtimes at or above 7.2.136-dc4', () => {
    // Given / When / Then
    expect(runtimeSupportsOrderedOAuthAliasPool('7.2.136-dc4')).toBe(true);
    expect(runtimeSupportsOrderedOAuthAliasPool('7.2.136-dc13')).toBe(true);
    expect(runtimeSupportsOrderedOAuthAliasPool('7.2.137-dc1')).toBe(true);
    expect(runtimeSupportsOrderedOAuthAliasPool('7.3.0-dc1')).toBe(true);
  });

  it('fails closed below the ordered-pool floor or on unparseable versions', () => {
    // Given / When / Then
    expect(runtimeSupportsOrderedOAuthAliasPool('7.2.136-dc3')).toBe(false);
    expect(runtimeSupportsOrderedOAuthAliasPool('7.2.136')).toBe(false);
    expect(runtimeSupportsOrderedOAuthAliasPool('7.2.135-dc9')).toBe(false);
    expect(runtimeSupportsOrderedOAuthAliasPool('')).toBe(false);
    expect(runtimeSupportsOrderedOAuthAliasPool('unknown')).toBe(false);
  });

  it('projects an ordered pool without throwing on a capable runtime', () => {
    // Given
    const pool = buildOrderedOAuthAliasPool('tier-medium', {
      provider: 'claude',
      model: 'claude-sonnet-5',
      fallback_chain: [{ provider: 'codex', model: 'gpt-5.6-terra' }],
    });

    // When
    const yaml = generateOrderedOAuthAliasPoolYaml(pool, { kind: 'ordered' });

    // Then
    expect(yaml).toContain('  claude:\n    - name: claude-sonnet-5\n      alias: tier-medium\n      fork: true');
    expect(yaml).toContain('  codex:\n    - name: gpt-5.6-terra\n      alias: tier-medium\n      fork: true');
  });

  it('preserves generated cross-channel aliases and antigravity aliases across regeneration', () => {
    // Given
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ccs-oauth-alias-pool-'));
    tempDirs.push(tempDir);
    const configPath = path.join(tempDir, 'cliproxy', 'config.yaml');
    const authDir = path.join(tempDir, 'cliproxy', 'auth');
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(
      configPath,
      `# CLIProxyAPI config generated by CCS v21\nport: 8317\noauth-model-alias:\n  antigravity:\n    - name: custom-agy\n      alias: custom-agy-alias\n  codex:\n    - name: gpt-5.5\n      alias: ccs-opus\n`,
      'utf8'
    );

    // When
    regenerateConfig(8317, { configPath, authDir });
    const first = fs.readFileSync(configPath, 'utf8').replace(/^# Generated: .*$/m, '');
    regenerateConfig(8317, { configPath, authDir });
    const second = fs.readFileSync(configPath, 'utf8').replace(/^# Generated: .*$/m, '');

    // Then
    expect(second).toBe(first);
    expect(second).toContain('name: custom-agy');
    expect(second).toContain('  codex:\n    - name: gpt-5.5\n      alias: ccs-opus');
  });
});
