import { describe, expect, it } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { modelPipelineRequestFixture } from '../../../config/schemas/__tests__/fixtures/model-pipeline-v3-fixture';
import {
  parseModelPipelinePublicationRequest,
  type ActiveIdentityV3,
  type ModelPipelineConfig,
  type PublicationReceiptV3,
} from '../../../config/schemas/model-pipeline';
import { createEmptyUnifiedConfig } from '../../../config/schemas/unified-config';
import { saveUnifiedConfig } from '../../../config/unified-config-loader';
import { sha256Digest } from '../../../utils/canonical-json';
import { projectModelRouting } from '../model-routing-projector';
import {
  CLIPROXY_CONFIG_VERSION,
  ORIGINAL_MANAGEMENT_PANEL_REPOSITORY,
  configNeedsRegeneration,
} from '../generator';

const request = parseModelPipelinePublicationRequest(modelPipelineRequestFixture());
const loadedAt = '2026-08-28T11:20:57Z';
const stagedConfigYaml = 'port: 8317\nmodel-routing:\n  schema-version: 3\n';

let testHome = '';
let originalCcsHome: string | undefined;

function cliproxyConfigPath(): string {
  return path.join(testHome, '.ccs', 'cliproxy', 'config.yaml');
}

function writeCliproxyConfig(content: string): void {
  writeFileSync(cliproxyConfigPath(), content, 'utf8');
}

function legacyCurrentConfig(): string {
  return `# CLIProxyAPI config generated by CCS v${CLIPROXY_CONFIG_VERSION}
port: 8317
panel-github-repository: ${ORIGINAL_MANAGEMENT_PANEL_REPOSITORY}
`;
}

function saveUnifiedConfigWith(pipeline?: ModelPipelineConfig): void {
  const config = createEmptyUnifiedConfig();
  if (pipeline) config.model_pipeline = pipeline;
  saveUnifiedConfig(config);
}

function persistedPipeline(): ModelPipelineConfig {
  const active: ActiveIdentityV3 = {
    generation: request.snapshot.generation,
    snapshot_digest: request.snapshot.snapshot_digest,
    projection_digest: projectModelRouting(request.snapshot)['projection-digest'],
    config_digest: sha256Digest(Buffer.from(stagedConfigYaml, 'utf8')),
  };
  const receipt: PublicationReceiptV3 = {
    schema_version: 3,
    ok: true,
    previous_active: null,
    active,
    snapshot_schema_digest: request.snapshot.snapshot_digest,
    routing_schema_digest: request.snapshot.inventory.routing_schema.digest,
    ccs_binary: { version: 'test', commit: 'test', built_at: loadedAt },
    cliproxy_binary: request.snapshot.inventory.binary_provenance,
    loaded_at: loadedAt,
  };
  return { schema_version: 3, snapshot: request.snapshot, receipt };
}

describe('configNeedsRegeneration model-pipeline ownership', () => {
  it('returns false while the canonical publication transaction owns config.yaml', () => {
    testHome = mkdtempSync(path.join(tmpdir(), 'ccs-pipeline-regen-'));
    originalCcsHome = process.env.CCS_HOME;
    process.env.CCS_HOME = testHome;
    mkdirSync(path.dirname(cliproxyConfigPath()), { recursive: true });
    writeCliproxyConfig('port: 8317\n');
    saveUnifiedConfigWith(persistedPipeline());

    expect(configNeedsRegeneration()).toBe(false);

    rmSync(testHome, { recursive: true, force: true });
    if (originalCcsHome === undefined) {
      delete process.env.CCS_HOME;
    } else {
      process.env.CCS_HOME = originalCcsHome;
    }
  });

  it('returns true for a markerless legacy config without an active pipeline', () => {
    testHome = mkdtempSync(path.join(tmpdir(), 'ccs-pipeline-regen-'));
    originalCcsHome = process.env.CCS_HOME;
    process.env.CCS_HOME = testHome;
    mkdirSync(path.dirname(cliproxyConfigPath()), { recursive: true });
    writeCliproxyConfig('port: 8317\n');
    saveUnifiedConfigWith();

    expect(configNeedsRegeneration()).toBe(true);

    rmSync(testHome, { recursive: true, force: true });
    if (originalCcsHome === undefined) {
      delete process.env.CCS_HOME;
    } else {
      process.env.CCS_HOME = originalCcsHome;
    }
  });

  it('returns false for a current legacy config without an active pipeline', () => {
    testHome = mkdtempSync(path.join(tmpdir(), 'ccs-pipeline-regen-'));
    originalCcsHome = process.env.CCS_HOME;
    process.env.CCS_HOME = testHome;
    mkdirSync(path.dirname(cliproxyConfigPath()), { recursive: true });
    writeCliproxyConfig(legacyCurrentConfig());
    saveUnifiedConfigWith();

    expect(configNeedsRegeneration()).toBe(false);

    rmSync(testHome, { recursive: true, force: true });
    if (originalCcsHome === undefined) {
      delete process.env.CCS_HOME;
    } else {
      process.env.CCS_HOME = originalCcsHome;
    }
  });

  it('returns false when config is absent, even with an active pipeline', () => {
    testHome = mkdtempSync(path.join(tmpdir(), 'ccs-pipeline-regen-'));
    originalCcsHome = process.env.CCS_HOME;
    process.env.CCS_HOME = testHome;
    saveUnifiedConfigWith(persistedPipeline());

    expect(configNeedsRegeneration()).toBe(false);

    rmSync(testHome, { recursive: true, force: true });
    if (originalCcsHome === undefined) {
      delete process.env.CCS_HOME;
    } else {
      process.env.CCS_HOME = originalCcsHome;
    }
  });
});
